# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b63a62e0189ce1479bc4fc48440f14e495b5b359df8483eea9a17e3a09db8abfc81fcdcc39da7f5cc921952af55cf4b029422c0c6bd6a82eceb7c82f67d6b59f

test:
  secret_key_base: 2d602c92b6501df4ac2b6661e8937c3f63b02222548c00c342d8fd35b0d02cc8b6c090d723ed9bda309812334059efc9215c1f3d01d4f1707738caa6a715f342

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
